name: Feature request
description: Something you want to see added to linux-tkg !
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to see linux-tkg get better!
  - type: dropdown
    id: check-duplicates
    attributes:
      label: Same-request check
      description: Have you checked that a similar request has been made ? If so, please chime-in there instead of opening another feature request.
      options:
        - 'Yes'
    validations:
      required: true
  - type: dropdown
    id: distro
    attributes:
      label: Linux Distribution affected
      description: What Distro would be affected by this addition ?
      options:
        - All
        - Archlinux
        - Ubuntu
        - Debian
        - Fedora
        - SUSE
        - Gentoo
        - Generic
      default: 0
    validations:
      required: true
  - type: textarea
    id: fature-description
    attributes:
      label: Feature description
      description: |
        Please describe the feature you want added here.

        Non-exhaustive list of questions:
        - What are the benefits
        - Any relevant links
        - Has someone benchmarked it (if applicable)
        - Are you willing to contribute this addition yourself
        - Ideas on the maintenance burden on such addition
    validations:
      required: true
  - type: dropdown
    id: frog
    attributes:
      label: My Favorite type(s) of frog
      multiple: true
      description: What is your favorite frog type ? If we disagree on this, your feature request may be entirely deserted, chose wisely...
      options:
        - Frog
        - African Bullfrog (Pyxicephalus adspersus)
        - African Dwarf Frog (Hymenochirus)
        - American Bullfrog (Lithobates catesbeianus)
        - American Cinchona Plantation Treefrog (Isthmohyla rivularis)
        - American Green Tree Frog (Dryophytes cinereus / Hyla cinerea)
        - American Toad (Anaxyrus americanus)
        - Blessed Poison Frog (Ranitomeya benedicta)
        - Bumblebee Dart Frog (Dendrobates leucomelas)
        - Common Frog (Rana temporaria)
        - Cranwell's Horned Frog (Ceratophrys cranwelli)
        - Desert Rain Frog (Breviceps macrops)
        - Glass Frog (Centrolenidae)
        - Golden Mantella (Mantella aurantiaca)
        - Goliath Frog (Conraua goliath)
        - Gray Tree Frogs (Hyla versicolor)
        - Gray Tree frog (Dryophytes versicolor)
        - Green Frog (Lithobates clamitans)
        - Madagascar Tomato Frog (Dyscophus antongilii)
        - Malayan Horned Frog (Megophrys nasuta)
        - Malayan Horned Frog (Pelobatrachus nasutus)
        - Mimic Poison Frog (Ranitomeya imitator)
        - Pacman Frog (Ceratophrys)
        - Painted Reed Frog (Hyperolius marmoratus)
        - Poison Dart Frogs (Dendrobatidae)
        - Red-Backed Poison Frog (Ranitomeya reticulata)
        - Red-Eyed Tree Frog (Agalychnis callidryas)
        - Shovel-Headed Tree Frog (Triprion spatulatus)
        - Spotted tree Frog (Nyctixalus pictus)
        - Strawberry Poison Dart Frog (Oophaga pumilio)
        - True Frogs (Ranidae)
        - Vietnamese mossy Frog (Theloderma corticale)
        - Waxy Monkey Frog (Phyllomedusa sauvagii)
        - Wood Frog (Lithobates sylvaticus)
      default: 0
    validations:
      required: true
